spring.application.name=CustomerProduct
spring.datasource.url=jdbc:mysql://localhost:3306/customerproduct
spring.datasource.username=root
spring.datasource.password=Pass@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ? JPA/Hibernate (correct keys with dashes)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param